Add solution for 04-spa/03-ScrollBehavior
js-tasks-ru/vue-20210511_anton024 pull request #20
Opened 2021-06-02 21:35 UTC by abagryanov

2021-06-02 21:36 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-03 22:04 UTC, ShGKme requested changes
Функция работает не совсем корректно.
Пишите, если не до конца понятно, как именно она должна работать и зачем в ней работа с мета-свойством.

2021-06-03 22:04 UTC, ShGKme commented on 04-spa/03-ScrollBehavior/router/index.js
> +      return false;
Отдельно проверять `to.matched.some` и `to.meta.saveScrollPosition` не нужно, так как сам маршрут `to` входит в массив `to.mached`. Аналогично с `from`.

Особой обработки ситуаций, когда ровно один из двух - to или from имеет мета свойство - не требуется, у такого случая нет особой обработки.

Есть только один случай, при котором мета свойство влияет на ответ. Когда и у to, и у from в mached есть saveScrollPosition. В этом случае требуется вернуть `false`.

Ваше решение проходит тестирование, но будто бы ориентируется на тесты, и условия подобраны под прохождение именно этих тестов.

Например, если будет только `to.meta.saveScrollPosition`, но будет и `hash`, то `hash` проигнорируется, будет переход к 0 в 57 строке.

Также не будет перехода, есть только у одного маршрута будет в цепочке мета свойство, так как в 60-61 строке стоит "или". Например, если бы переход был с какого-то маршрута на программу, где в цепочке есть мета свойство - прокрутки вверх не будет.

2021-06-03 23:32 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-03 23:33 UTC, abagryanov commented on 04-spa/03-ScrollBehavior/router/index.js
> +      return false;
> Отдельно проверять `to.matched.some` и `to.meta.saveScrollPosition` не нужно, так как сам маршрут `to` входит в массив `to.mached`. Аналогично с `from`.
> 
> Особой обработки ситуаций, когда ровно один из двух - to или from имеет мета свойство - не требуется, у такого случая нет особой обработки.
> 
> Есть только один случай, при котором мета свойство влияет на ответ. Когда и у to, и у from в mached есть saveScrollPosition. В этом случае требуется вернуть `false`.
> 
> Ваше решение проходит тестирование, но будто бы ориентируется на тесты, и условия подобраны под прохождение именно этих тестов.
> 
> Например, если будет только `to.meta.saveScrollPosition`, но будет и `hash`, то `hash` проигнорируется, будет переход к 0 в 57 строке.
> 
> Также не будет перехода, есть только у одного маршрута будет в цепочке мета свойство, так как в 60-61 строке стоит "или". Например, если бы переход был с какого-то маршрута на программу, где в цепочке есть мета свойство - прокрутки вверх не будет.

Да, я криво как-то прочитал задачу. Не сразу понял что нужно. Ночные бдения... Пофиксил, надеюсь верно )

2021-06-04 05:14 UTC, ShGKme approved these changes
Принято 👍

2021-06-04 05:14 UTC, merged