Add solution for 04-spa/04-Layouts
js-tasks-ru/vue-20210511_anton024 pull request #21
Opened 2021-06-05 23:00 UTC by abagryanov

2021-06-05 23:00 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-11 17:26 UTC, abagryanov commented
@ShGKme Чекните?

2021-06-12 10:04 UTC, ShGKme requested changes
По сути задачи всё верно, но немного не соответствует вёрстка.

Если будете потом собирать всё в готовый проект, лучше поправить сразу, чтобы потом не искать проблемы в большом коде.

Если нет, могу принять так

2021-06-12 10:04 UTC, ShGKme commented on 04-spa/04-Layouts/components/AuthLayout.vue
> +}
`page` в общих стилях, его можно не добавлять.

2021-06-12 10:04 UTC, ShGKme commented on 04-spa/04-Layouts/components/FormLayout.vue
> +    <slot></slot>
Шаблон не много соответствует вёрстке.
https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/meetup-form.html#L25-L27

2021-06-12 10:04 UTC, ShGKme commented on 04-spa/04-Layouts/components/AuthLayout.vue
> +    <h1>{{ title }}</h1>
Шаблон немного не соответствует вёрстке:
https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/login.html#L24-L26

2021-06-12 10:04 UTC, ShGKme commented on 04-spa/04-Layouts/components/BaseLayout.vue
> +    <the-footer></the-footer>
Слот нужно обернуть в `<main class="main">`. Это растянет основную часть страницы, когда контент меньше высоты экрана.

2021-06-12 10:04 UTC, ShGKme commented on 04-spa/04-Layouts/components/TheHeader.vue
> +    </div>
Логотип - изображение с ссылкой на главную: https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/login.html#L13-L15

Можно взять готовый код с вебинара:
https://github.com/js-tasks-ru/vue-course-materials/blob/master/04-spa/03-vue-router/src/App.vue#L6-L10

2021-06-12 10:04 UTC, ShGKme commented
> @ShGKme Чекните?

Прошу прощения за задержку, потерялся PR

2021-06-14 18:44 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-14 18:45 UTC, abagryanov commented
@ShGKme Поправил. Спасибо что дали комментарии. Сначала не нашел примеры верстки.

2021-06-14 19:03 UTC, ShGKme approved these changes
Принято 👍

2021-06-14 19:03 UTC, ShGKme commented on 04-spa/04-Layouts/components/TheHeader.vue
> +        </router-link>
Логотип можно не копировать, если обращаться к нему из `src/assets/images/logo.svg`. Можно по относительному пути (`../../../src/assets/images/logo.svg`), либо использовать алиас (`@/assets/images/logo.svg`)

2021-06-14 19:03 UTC, merged